"""removes unique constrain from ticket tablet

Revision ID: 6a2c22a4ff28
Revises: a93f46d9a631
Create Date: 2025-12-03 16:33:49.975492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a2c22a4ff28"
down_revision: Union[str, None] = "a93f46d9a631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ticket_customer_id", table_name="ticket")
    op.drop_index("ix_ticket_id", table_name="ticket")
    op.drop_index("ix_ticket_ticket_id", table_name="ticket")
    op.drop_table("ticket")
    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_id", table_name="user")
    op.drop_index("ix_user_name", table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="user_pkey"),
    )
    op.create_index("ix_user_name", "user", ["name"], unique=False)
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    op.create_table(
        "ticket",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "customer_id", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("channel", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "subject", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "priority", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "short_description",
            sa.VARCHAR(length=141),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_urgent", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("agent", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="ticket_pkey"),
    )
    op.create_index("ix_ticket_ticket_id", "ticket", ["ticket_id"], unique=False)
    op.create_index("ix_ticket_id", "ticket", ["id"], unique=False)
    op.create_index("ix_ticket_customer_id", "ticket", ["customer_id"], unique=True)
    # ### end Alembic commands ###
